name: ci
on:
  - push

env:
  JAVA_TARGET_VERSION: 17

jobs:
  build:
    name: Setup and Build
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 📦 Checkout
        uses: actions/checkout@v3

      - name: 'Set up latest Oracle JDK 17'
        uses: oracle-actions/setup-java@v1.1.2
        with:
          website: oracle.com
          release: 17

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
            ${{ runner.os }}-gradle

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test
        run: |
          ./gradlew build dockerPush
